export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Chats} from "./Chats"
export {default as Profile} from "./Profile"
export {default as People} from "./People"